
package GUI;
/*
aqui se encuentran todas y cada una de las diferentes librerias que fueron utilizadas para la
realizacion de nuestras interfaces, y el llamado de los diferentes packages donde haciamos el llamado de los
diferentes metodos para la buen funcionamiento de la logica de esta interfaz 
*/
import LOGICA.gestionar_personas;
import LOGICA.gestionar_personas_ME;
import LOGICA.gestionar_servicio;
import static Main.Main_p.c;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
//////////////////////////////////////////////////////////////////////////////////////////////
/**
 *@author Moreno Romero Miguel Angel 
 * miguel.romero@correounivalle.edu.co
 *@author Valencia Pardo Sergio 
 * sergio.pardo@correounivalle.edu.co
 *@author Valderrama Jorde Enrique
 * jorge.valderrama@correounivalle.edu.co
 */
/////////////////////////////////////////////////////////////////////////////////////////////
/*
nos encontramos nuestra clase principal "MENU " que es la encargada de contener 
la fucionalidad y metodos necesarios para la funcioniladad de nuestra interfaz que es la encargada de unificar las otras interfaces graficas 
*/
public class MENU extends javax.swing.JFrame {

    
//inicializamos las interfaces y le colocamos un nombre que nos quede facil de llamar en los eventos de los botones     
    
public static GUI_servicio registro;
public static gestionar_servicio servico;


public static GUI_personas p;
public static gestionar_personas g;
  

public static GUI_personasME m;
public static gestionar_personas_ME h;


/*
una vez que hemos declarado nuestra variable tipo entero (int) y llamado  nuestros metodos antes incializados 
procedemos a inicializar nuestra clase que estara declara al final de todo el codigo que es la responsable 
de pasar una imagen de fondo a nuestro panel principal 
*/ 

 imagen_fondo x = new imagen_fondo();
 /*
una vez declarado todas los metodos que vamos a utilizar procedemos a inicializar en nuestro "CONSTRUCTOR" la clase 
responsable de inicializar nuestos elementos del JFrame, el fondo de nuestro JPanel y de colocar los datos visibles
en nuestra JTable apenas aparezca nuestra interfaz.    
*/
    public MENU() {
        
        this.setContentPane(x);
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ME = new javax.swing.JButton();
        GA = new javax.swing.JButton();
        GC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);

        ME.setBackground(new java.awt.Color(255, 204, 102));
        ME.setText("GESTIONAR MEDICOS/B ESPECIALISTAS ");
        ME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 8));
        ME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEActionPerformed(evt);
            }
        });

        GA.setBackground(new java.awt.Color(255, 204, 102));
        GA.setText("GESTIONAR AFILIADOS");
        GA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204), 8));
        GA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAActionPerformed(evt);
            }
        });

        GC.setBackground(new java.awt.Color(255, 204, 102));
        GC.setText("GESTIONAR CITAS");
        GC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 8, true));
        GC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("BIENVENIDO ESCOGE QUE QUIERES GESTIONAR HOY :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GA, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ME, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GC, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ME, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAActionPerformed
/*
aqui solo hacemos el llamado de nuestra interfaz que gestionan los afiliados del servicio medico         
        */       
    
        c.setVisible(false);
        p = new GUI_personas();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        p.setResizable(false);
        g = new gestionar_personas(p);
  
 



        // TODO add your handling code here:
    }//GEN-LAST:event_GAActionPerformed

    private void GCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCActionPerformed
/*
aqui solo hacemos el llamado de nuestra interfaz que gestiona las citas de nuestros afiliados del servicio medico         
        */ 
        c.setVisible(false);
        registro = new GUI_servicio();
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
        registro.setResizable(false);
        servico = new gestionar_servicio(registro);




        // TODO add your handling code here:
    }//GEN-LAST:event_GCActionPerformed

    private void MEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEActionPerformed
/*
aqui solo hacemos el llamado de nuestra interfaz que gestiona los medicos y especialistas de nuestro servicio medico          
        */ 
        c.setVisible(false);
        m = new GUI_personasME();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setResizable(false);
        h = new gestionar_personas_ME(m);


        // TODO add your handling code here:
    }//GEN-LAST:event_MEActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GA;
    private javax.swing.JButton GC;
    private javax.swing.JButton ME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
/*
ahora aqui declaramos nuestra clase "Imagen_Fondo" que es la que utilizaremos para pasar le una imagen anuestro JPanel 
para darle un mejor entorno visual a nuestra intrfaz grafica la cual fue inicializada al inicio del codigo y llamada
para su ejecucion en el constructor.     
*/
    
class imagen_fondo extends JPanel{
    private Image imagen;
    //metodo 
    public void paint (Graphics g){
        imagen = new ImageIcon(getClass().getResource("/IMAGENES/fondo.png")).getImage();
        g.drawImage(imagen,0, 0, getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
    
}

}
